# Generated by Django 4.2.30 on 2026-07-17 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facturas", "0007_factura_emitida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_nota", models.CharField(max_length=20, unique=True)),
                ("es_debito", models.BooleanField(default=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("iva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("emitida", models.BooleanField(default=False)),
                ("lugar_emision", models.CharField(editable=False, max_length=100)),
                ("fecha_emision", models.DateField(editable=False)),
                ("nombre_cliente", models.CharField(editable=False, max_length=100)),
                ("telefono_cliente", models.CharField(editable=False, max_length=11)),
                ("cedula_cliente", models.CharField(editable=False, max_length=11)),
                (
                    "factura_afectada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facturas.factura",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos",
                        to="notas_de_debito_credito.nota",
                    ),
                ),
            ],
        ),
    ]
